name: Build dylib
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Theos
      run: |
        export THEOS=${{ github.workspace }}/theos
        echo "THEOS=$THEOS" >> $GITHUB_ENV
        git clone --recursive https://github.com/theos/theos.git $THEOS
        wget -q https://github.com/theos/sdks/archive/master.zip
        unzip master.zip -d $THEOS/sdks
        mv $THEOS/sdks/sdks-master/*.sdk $THEOS/sdks/
    - name: Build
      run: |
        export THEOS=${{ github.workspace }}/theos
        export PATH=$THEOS/bin:$PATH
        make
    - name: Upload dylib
      uses: actions/upload-artifact@v4
      with:
        name: LustSpeed.dylib
        path: ./.theos/obj/LustSpeed.dylib
